### ISSUE TITLE
Fiji 2.16.0 checklist

### ISSUE THREAD

**Issue by ctrueden** [fiji/fiji#337]
Definite:
* [x] Stuff @gselzer needs (scijava-search, ...)
* [ ] BigStitcher
* [ ] sciview (with soft Java 11 requirement)
* [ ] BIG components
* [ ] 3DScript
* [x] SciJava Ops

Ideal:
* [x] New Jaunch launcher (side by side with existing launcher for now)
* [ ] [fiji:// lijnks + Fiji core rebranding](https://forum.image.sc/t/fiji-links-and-the-naming-of-fiji-imagej2/88667/9)
* [x] Update bundled Java to version 21

**Comment by ctrueden** [comment]
Fiji 2.16.0 was released as part of the impending update to Java 21. Some of the items above have still not been fully addressed, but it is all much closer now.

**Comment by ctrueden** [comment]
This issue seems kind of incoherent to me at this point, because I didn't give much context regarding what needs to be done. Fiji 2.16.0 is long released, and the Java 21 update is quite far along now. So I'm going to close this in favor of the [Fiji Fit project board](https://github.com/orgs/fiji/projects/1) in general.
