### ISSUE TITLE
Fiji Link supports

### ISSUE THREAD

**Issue by mzouink** [fiji/fiji#343]
# Thread for Fiji Link support:
![image](https://github.com/fiji/fiji/assets/5658590/929ef17d-994a-4360-be39-ff7513da9a13)

## Goal :
- Enable workflow sharing
- Enable accurate reproduction across various image processing and visualization settings. 

## Approach :
![image](https://github.com/fiji/fiji/assets/5658590/107b3fed-a6ff-4c09-8caf-3925afe9a8b4)

### Discussion: https://forum.image.sc/t/fiji-links-and-the-naming-of-fiji-imagej2/88667

# TODO: 
- [ ]  @ctrueden : Check and integrate this service for Windows supports [HERE](https://github.com/mzouink/fiji-windows-scheme/blob/main/src/main/java/sc/fiji/links/WindowsSchemeRegisterUsingCommand.java)
Specially: [getFijiPath()](https://github.com/mzouink/fiji-windows-scheme/blob/014a0987b188d2003e124536074115516f5ac862/src/main/java/sc/fiji/links/WindowsSchemeRegisterUsingCommand.java#L123)
We will **not** use [Advapi32Util based ](https://github.com/mzouink/fiji-windows-scheme/blob/014a0987b188d2003e124536074115516f5ac862/src/main/java/sc/fiji/links/WindowsSchemeRegister.java)
- [ ]  @ctrueden : Merge this commit master for lunix https://github.com/fiji/fiji/pull/333/commits/a596d583f97b99e3a6699ce50486f45bdf62ecfd
- [ ]  @ctrueden: merge this commit for MacOS https://github.com/fiji/fiji/pull/333/commits/c6cf62eeebbc4a41383a052d46a15949be88b12a
- [ ]  @mzouink: Add unit test [here](https://github.com/scijava/scijava-common/tree/link-schemes) 
- [ ]  @mzouink: for MacOS, add Java version check

**Comment by mzouink** [comment]
thank you so much curtis (deeply sorry i wasn't much helpful this two weeks)
excited to push again on it

**Comment by aswallace** [comment]
Hi, wanted to check if there are any updates on plans for this feature! Our project would benefit from being to be able to use `fiji://` links, so we'd be happy to get involved with developing on it. Thanks!

**Comment by mzouink** [comment]
Hi @aswallace,  
Very glad you're willing to invest time in the project and help push it forward!

To enable the custom URI scheme `fiji://`, we needed to implement support in three areas, following the general pattern:

fiji://[PLUGIN]/[ARGS]

---

### 1. OS-Level URI Registration (`fiji://`)

Each OS requires a different approach:

- **macOS & Linux**  
  - Handled via this PR: [fiji/fiji#333](https://github.com/fiji/fiji/pull/333/files)  
  - ⚠️ Not yet tested on Linux.

- **Windows**  
  - I created a small service-based registration tool:  
    [fiji-windows-scheme](https://github.com/mzouink/fiji-windows-scheme/blob/main/src/main/java/sc/fiji/links/WindowsSchemeRegisterUsingCommand.java)  
  - This could be improved using Java 9+ APIs for tighter integration.

---

### 2. Fiji Plugin Dispatch (`[PLUGIN]`)

- @ctrueden started a service to handle plugin resolution:  
  👉 [scijava/scijava-links](https://github.com/scijava/scijava-links)  
- This dispatches the plugin part of the URI to the appropriate Fiji plugin.  
- 🧪 Needs further testing.

---

### 3. Plugin-Level Implementation (`[ARGS]`)

#### Example: BigDataViewer Integration

- @tpietzsch is working on serialization support:  
  🔗 [PR #205](https://github.com/bigdataviewer/bigdataviewer-core/pull/205)

- I added:
  - Link generation: [PR #207](https://github.com/bigdataviewer/bigdataviewer-core/pull/207)  
  - Link service: [bigdataviewer-links](https://github.com/bigdataviewer/bigdataviewer-links)

---

Happy to help with further development or testing and feel free to come up with a new process

**Comment by SeanDuHare** [comment]
@ctrueden is considered done? Also, tagging [the repository you created for this](https://github.com/fiji/fiji-links) for visibility in case others come looking here.
